# -*- coding: utf-8 -*-
"""Use_Tensors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1Pci7PXtvgJvyrsoDcug1ADg3OVDqcR

#Building DR using Word2vec model
"""

# Importing libraries
from gensim.models import Word2Vec
from sklearn.decomposition import PCA
from matplotlib import pyplot

# Defining the training data

sentences = [['We', 'went', 'to', 'the', 'beach', 'on', 'a', 'sunny', 'day'],
	['There', 'were', 'many', 'tourists', 'on', 'the', 'beach'],
	['We', 'went', 'to', 'the', 'nearby', 'museum', 'with', 'other', 'tourists']]

# Training the model  

model = Word2Vec(sentences, min_count=1)   
print(model)

# Fitting a 2D PCA model to the vectors

X = model[model.wv.vocab]  
print(X)                             
pca = PCA(n_components=2)   
print(pca)                       
result = pca.fit_transform(X)
print(result)

# Creating a scatter plot of the projection

pyplot.scatter(result[:, 0], result[:, 1])
words = list(model.wv.vocab)
print(words)
for i, word in enumerate(words):
  pyplot.annotate(word, xy=(result[i, 0], result[i, 1]))
pyplot.show()

